# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  EpicTracer_config = debug
endif
ifeq ($(config),release)
  EpicTracer_config = release
endif

PROJECTS := EpicTracer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

EpicTracer:
ifneq (,$(EpicTracer_config))
	@echo "==== Building EpicTracer ($(EpicTracer_config)) ===="
	@${MAKE} --no-print-directory -C EpicTracer -f Makefile config=$(EpicTracer_config)
endif

clean:
	@${MAKE} --no-print-directory -C EpicTracer -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   EpicTracer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"